version: 2
updates:
- package-ecosystem: npm
  directory: "/cli"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
