# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
      working-directory: server
    - run: npm run build --if-presentci
      working-directory: server
    - run: npm run lint
      working-directory: server
    - run: npm run test
      working-directory: server
    - uses: codecov/codecov-action@v1
      with:
        files: ./server/coverage/clover.xml
        name: server
        fail_ci_if_error: true
